version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ais_db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  api:
    container_name: ais-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: ais-api
    depends_on:
      - db
      - cache
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/ais_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://cache:6379
    links:
      - db
      - cache
volumes:
  db:
    driver: local
  cache:
    driver: local
